# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI manager for frp client and server
LUCI_DEPENDS:=+luci-base +frp

PKG_VERSION:=2026.07.21
PKG_LICENSE:=Apache-2.0
PKG_RELEASE:=2

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
