include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-ddns-go
PKG_VERSION:=1.0.0
PKG_RELEASE:=3
PKG_PO_VERSION:=1.0.0-r3

LUCI_TITLE:=Native LuCI management for DDNS-GO
LUCI_DEPENDS:=+ddns-go +rpcd +ucode
LUCI_PKGARCH:=all
PKG_MAINTAINER:=ysuolmai

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
